AMS/Pages/Report/Report.cshtml.cs
using AMS.Model;
using AMS.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AMS.Pages.Report
{
    public class ReportModel : PageModel
    {
        private readonly ReportService _reportService;

        public ReportModel(ReportService reportService)
        {
            _reportService = reportService;
        }

        public List<VoucherViewDTO> Vouchers { get; set; }

        public async Task OnGetAsync()
        {
            Vouchers = await _reportService.GetVoucherListAsync();
        }


        public async Task<IActionResult> OnPostExport()
        {
           
            var exportData =await _reportService.GetVoucherListAsync(); 

            var stream = _reportService.ExportToExcelFromList(exportData);

            return File(
                stream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "VoucherReport.xlsx"
            );
        }
    }
}

AMS/Pages/Report/Report.cshtml
@page
@model ReportModel
@{
    ViewData["Title"] = "Create Voucher";
}

<h3>Voucher List</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Voucher #</th>
            <th>Date</th>
            <th>Ref No</th>
            <th>Type</th>
            <th>Account</th>
            <th>Debit</th>
            <th>Credit</th>
            <th>Narration</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Vouchers)
        {
            <tr>
                <td>@item.VoucherID</td>
                <td>@item.VoucherDate.ToString("yyyy-MM-dd")</td>
                <td>@item.ReferenceNo</td>
                <td>@item.VoucherType</td>
                <td>@item.AccountName</td>
                <td>@item.DebitAmount.ToString("N2")</td>
                <td>@item.CreditAmount.ToString("N2")</td>
                <td>@item.Narration</td>
            </tr>
        }
    </tbody>
</table>


<form method="post" asp-page-handler="Export">
    <button type="submit">Export to Excel</button>
</form>